### PR TITLE
add darkfi

### PR DESCRIPTION
**Pull request by narodnik**
add darkfi

### CODE REVIEW

**Comment by Aimeedeer** [comment]
Thanks @narodnik!

Would you please go ahead and send us more information about this project?
- [rib-bible](https://github.com/rust-in-blockchain/rust-in-blockchain/blob/master/rib-bible.md)
- [ribbot-config](https://github.com/rust-in-blockchain/ribbot/blob/master/src/rib-config.toml)

**Comment by narodnik** [comment]
thanks, should I open a PR on the ribbot repo as well?

**Comment by Aimeedeer** [comment]
> thanks, should I open a PR on the ribbot repo as well?

Yes, please. Thank you!

**Comment by narodnik** [comment]
Done. Thank you for your help. It's much appreciated.

**Pull request merged**
